version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errorlint
    - gosec
    - govet
    - ineffassign
    - revive
    - sqlclosecheck
    - staticcheck
    - unused

formatters:
  enable:
    - gofmt
    - goimports
